apiVersion: v1
kind: Service
metadata:
  name: my-java-app-service
spec:
  type: LoadBalancer # Tạo ra 1 Application Load Balancer (ALB)
  selector:
    app: my-java-app
  ports:
    - protocol: TCP
      port: 80       # Cổng bên ngoài (ALB)
      targetPort: 8080 # Cổng của ứng dụng (trong container)